name = "Phenology"
uuid = "d63380a9-e012-46f8-9dac-53fac26854bd"
authors = ["ArnaudG0649 <arnaudcmc@hotmail.com> and contributors"]
version = "0.0.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[extensions]
CairoMakieExt = "CairoMakie"

[compat]
CSV = "0.10.15"
CairoMakie = "0.15.6"
ConcreteStructs = "0.2.3"
DataFrames = "1.8.1"
DataFramesMeta = "0.15.5"
Dates = "1.11.0"
DifferentiationInterface = "0.7.11"
Distributions = "0.25.122"
FileIO = "1.17.1"
FiniteDiff = "2.29.0"
ForwardDiff = "1.3.0"
JLD2 = "0.6.2"
Optimization = "5.1.0"
OptimizationBBO = "0.4.5"
OptimizationOptimJL = "0.4.8"
XLSX = "0.10.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
